go的错误处理这块在日常中被大家吐槽较多的地方，比较严重的是在各层级的逻辑代码中对错误的处理有些重复

比如：有人写代码就会在每一层都判断错误并记录日志，从代码层面看，貌似很严谨，但是如果看日志会发现一堆重复的信息，
    等到排查问题时反而造成干扰

[go代码错误处理相关的最佳实践] 3点

error类型是一个内建接口类型，该接口只规定了一个返回字符串值的error方法
    type error interface{
        Error()string
    }
    go语言的函数经常返回一个error值，调用者通过测试error值是否是nil来进行错误处理。
    if err!=nil{
        todo
    }
    err为非nil，表示存在错误。
    

[自定义错误要实现error接口]
我们经常会定义符合自己需要的错误类型，但是记住要让这些类型实现error接口，这样就就不用再调用方的程序里引入额外的类型。

举个栗子：
    
    `
    package myerror
    import(
        "fmt"
        "time"
    )
        
    type myError struct{
        Code int
        When time.time
        What string
    }
    func (e *myError)Error()string{
        return fmt.Sprintf("at %v, %s,code %d,e.when,e.what,e.code)
    }
    
    // 如果myError没有实现error接口的话，这里的返回值类型就要定义成myError类型。
    // 紧接着调用者TryIt程序里就要通过myError.Code==xxx来判断到底是那种具体类型的错误
    // 那调用者判断自定义error是具体那种错误的时候应该怎么办呢？myError并未向包外暴露，答案是通过向包外暴露
    // 检查错误行为的方法来实现. 如 myerror.IsXXXXError(err)；或者是通过比较error本身与包外暴露的常量错误是否相等来判断
    // 比如：操作文件时常用来判断文件是否结束的io.EOF
    // 类似的还有gorm.ErrRecordNotFound等各种开源包对外暴露的错误常量
    func run()error{
        rerurn &myError{
            1002,
            time.now(),
            "id didn`t work"
    }

    func TryIt(){
        if err:=run();err!=nil{
            fmt.Println(err)
        }
    }

    }

[错误处理常犯的错误]

    func WriteAll(w io.Writer, buf []byte) error {
        _, err := w.Write(buf)
        if err != nil {
            log.Println("unable to write:", err) // annotated error goes to log file
            return err                           // unannotated error returned to caller
        }
        return nil
    }

    func WriteConfig(w io.Writer, conf *Config) error {
        buf, err := json.Marshal(conf)
        if err != nil {
            log.Printf("could not marshal config: %v", err)
            return err
        }
        if err := WriteAll(w, buf); err != nil {
            log.Println("could not write config: %v", err)
            return err
        }
        return nil
    }

    func main() {
        err := WriteConfig(f, &conf)
        fmt.Println(err) // io.EOF
    }

上面程序的错误处理暴露了两个问题：
1、 底层函数WriteAll在发生错误后，除了向上层返回错误外，还向日志里记录了错误，上层调用者做了同样的事情，记录日志
    然后把错误返回给程序顶层
    因此在日志中得到了一对重复的内容：
    unable to write: io.EOF
    could not write config: io.EOF
    ...

2、在程序的顶部，虽然得到了原始错误，但没有相关内容，换句话说没有把WriteAll、WriteConfig记录到log里的那些信息包装到错误里，返回给上层。
    
    针对这连个问题的解决方案可以是，在底层函数WriteAll、WriteConfig中给发生的错误添加上下文信息，然后将错误返回上层，
    由上层程序最后处理这些错误。
    
    一种简单的包装错误的方法是使用fmt.Errorf函数，给错误添加注解信息
    
    func WriteConfig(w io.Writer,conf *Config)error{
       buf,err:= json.marshal(conf)
        if err !=nil{
            // 添加了错误发生的位置+err
            return fmt.Errorf("could not marshal config:%v",err)
        }
            // 是在write config发生的错误+err
        if err :=WriteAll(w,buf);err!=nil{
            return fmt.Errorf("could not write config:%v",err)
        }
        return nil
    }
    
    func WriteAll(w io.wirter,buf []byte)error{
        _,err:=w.write(buf)
        if err!=nil{
            return fmt.Errorf("write failed:%v",err)
        }
        return nil
    }

[给错误附加上下文信息]
    fmt.Errorf只是给错误添加了简单的注解信息，如果在想在添加信息的同时还加上错误的调用栈，
    可以借助github.com/pkg/errors 这个包提供的错误包装能力
    
    包装方法：
    //只附加新的信息
    func WithMessage(err error, message string) error
    
    //只附加调用堆栈信息
    func WithStack(err error) error
    
    //同时附加堆栈和信息
    func Wrap(err error, message string) error

    解包方法：
    cause方法会返回包装错误对应的最原始错误--即会递归地进行解包
    func Cause(err error) error

    以下是使用github.com/pkg/errors改写后的错误处理程序
    
    func ReadFile(path string)([]byte,error){
        f,err:=os.Open(path)
        if err!=nil{
            return nil,errors.Wrap(err,"open failed")
        }

        defer f.close()
        buf,err:=ioutil.ReadAll(f)
        if err!=nil{
            return nil,errors.Wrap(err,"read failed")
        }
        return buf,nil
    }

    func ReadConfig()([]byte,error){
        home:=os.Getenv("HOME")
        config,err；=ReadFile(filepath.Join(home,".setting.xml"))
        return config,errors.WithMessage(err,"could not read config")
    }
    
    func main(){
        _,err:=ReadConfig()
        if err!=nil{
            fmt.Printf("original error:%T %v\n",errors.Cause(err),errors.Cause(err))
            fmt.Printf("stack trace:\n%+v\n",err)
            os.Exit(1)
        }
    }
    
    上面格式化字符串时用的 %+v 是在 % v 基础上，对值进行展开，即展开复合类型值，比如结构体的字段值等明细。
    这样既能给错误添加调用栈信息，又能保留对原始错误的引用，通过Cause可以还原到最初始引发错误的原因。
    
